### ISSUE TITLE
Cannot aquire signal and decode when using more than 2 demodulators

### ISSUE THREAD

**Issue by invader-zimm** [cropinghigh/sdrpp-inmarsatc-demodulator#2]
When having one or two demodulators, everything seems to work fine. But if I add one more, the third one doesn't seem to work. I tuned it to exactly the same frequencies which worked for the other two, and it looks like it fails to lock on, the constellation looks like this:
![2022-09-17-174242](https://user-images.githubusercontent.com/76672128/190925565-62f8e6ea-a288-4a45-a7ee-3c7c499e407d.png)

If tune the demod VFO a bit up or down, away from the correct frequency, the constellation will eventually look like expected but it still doesn't decode anything no matter how long I leave it running.

Another thing, I'm not sure if this is a bug or not: when having multiple demodulators, the last decoded frame number is the same for all of them, including the demodulators which do not decode anything. Since all VFOs are tuned to different LES channels, I though the frame numbers should be different, no?

**Comment by cropinghigh** [comment]
1. Possible that third one not locks because of the bug i haven't solved yet: after some time of working(changing frequency) decoder just stops decoding anything.
2. All LES channels have the same frame number in every moment, that's true. But untuned demodulator should show nothing. Possible problem in that every module is using same decoder.

**Comment by invader-zimm** [comment]
I noticed that even with only one demod active, if I tune to different frequencies 4-5 times in a row (by double-clicking bookmarks in the Frequency Manager) the demod would lock on the signal but not decode. But I'm not sure it's related to this issue, in the screenshot I posted there are 3 demods, the first 2 were active and decoding frames for about 5 hours continuously. Only the third demod was not working.

Is it possible that instead of having multiple demod modules, to have only one module which can support multiple VFOs? Would that work better?

**Comment by cropinghigh** [comment]
1. Yes, it's related. As i said, there is an unfixed bug that makes decoder unusable after some frequency changes. 
2. No, it would not fix internal issue.

**Comment by cropinghigh** [comment]
Maybe [0fa0e55](https://github.com/cropinghigh/sdrpp-inmarsatc-demodulator/commit/0fa0e55133d649151bccf78f3f8c43272c9b3d1a) fixed that problem

**Comment by cropinghigh** [comment]
f3655ac very likely fixed that

**Comment by invader-zimm** [comment]
Yes the issue looks fixed. I tried with 4 demodulators, tuning them to different frequencies, changing frequencies, and they all locked on the signal and started decoding as expected.
Thank you for the fix!
